option stop dbus service
icasdri/mpris2controller pull request #7
Opened 2019-03-21 21:37 UTC by gutierri

2019-04-03 18:54 UTC, icasdri requested changes
Thanks for the pull request! Quick question: what is your use case for a Quit method?
Looking forward to pulling this :)

2019-04-03 18:54 UTC, icasdri commented on mpris2controller/controller.py
> +    def __init__(self, bus, loop = None, call=None):
Please follow PEP8 style for keyword arguments, i.e. `loop=None` :)

2019-04-03 18:54 UTC, icasdri commented on mpris2controller/controller.py
> +        log.info("Stop main loop")
Just one log message before (like the other methods) should be sufficient :)

2019-04-03 18:54 UTC, icasdri commented on mpris2controller/controller.py
> +        log.info("Stop main loop")
Also, maybe this method should be called `Quit` on DBUS ("stop loop" seems implementation-specific, and just "stop" might be confused with MPRIS stop)

2019-04-03 20:02 UTC, gutierri commented
In the meantime, I was testing things, developing and feeling a 
difficulty in stopping the service or reigning.
Putting a command to terminate the DBUS service seems to be an 
acceptable solution.

On 4/3/19 3:54 PM, Derek W wrote:
>
> *@icasdri* requested changes on this pull request.
>
> Thanks for the pull request! Quick question: what is your use case for 
> a Quit method?
> Looking forward to pulling this :)
>
> ------------------------------------------------------------------------
>
> In mpris2controller/controller.py 
> <https://github.com/icasdri/mpris2controller/pull/7#discussion_r271881509>:
>
> > @@ -54,8 +54,9 @@ def call(self, method_name):
>   
>   
>   class Controller(dbus.service.Object):
> -    def __init__(self, bus, call=None):
> +    def __init__(self, bus, loop = None, call=None):
>
> Please follow PEP8 style for keyword arguments, i.e. |loop=None| :)
>
> ------------------------------------------------------------------------
>
> In mpris2controller/controller.py 
> <https://github.com/icasdri/mpris2controller/pull/7#discussion_r271881939>:
>
> > @@ -171,6 +172,12 @@ def call_on_head_not_playing(self, method_name):
>               else:
>                   self.remove(cur)
>   
> +    @dbus.service.method(dbus_interface=MY_INTERFACE)
> +    def StopLoop(self):
> +        log.info("Stop main loop")
>
> Just one log message before (like the other methods) should be 
> sufficient :)
>
> ------------------------------------------------------------------------
>
> In mpris2controller/controller.py 
> <https://github.com/icasdri/mpris2controller/pull/7#discussion_r271882422>:
>
> > @@ -171,6 +172,12 @@ def call_on_head_not_playing(self, method_name):
>               else:
>                   self.remove(cur)
>   
> +    @dbus.service.method(dbus_interface=MY_INTERFACE)
> +    def StopLoop(self):
> +        log.info("Stop main loop")
>
> Also, maybe this method should be called |Quit| on DBUS ("stop loop" 
> seems implementation-specific, and just "stop" might be confused with 
> MPRIS stop)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/icasdri/mpris2controller/pull/7#pullrequestreview-222388603>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABD1PC1Hv6ESQK6Vi4EX8ENPC80GSb5iks5vdPj7gaJpZM4cCbCO>.
>

2019-04-04 17:02 UTC, icasdri approved these changes
Cool, thanks!

2019-04-04 17:03 UTC, merged